In [1]:
import numpy as np

In [2]:
#collect data
x= np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])

y = np.array([[0],
             [1],
             [1],
             [0]])

In [6]:
print (x)
print('   ')
print (y)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
   
[[0]
 [1]
 [1]
 [0]]


In [8]:
#build model

num_epochs = 60000
#initialize weights
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

In [9]:
print (syn0)
print(' ')
print(syn1)

[[-0.86535467 -0.29025639 -0.03222596  0.9330428 ]
 [-0.41482975  0.87361917 -0.87321201  0.9460677 ]
 [ 0.63550084 -0.40904256  0.25089371  0.49554198]]
 
[[ 0.62772396]
 [ 0.73853532]
 [-0.58487008]
 [-0.20246878]]


In [19]:
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    
    return 1/(1+np.exp(-x))

In [30]:
#step3 Train Model

for j in range(num_epochs):
    #feed forward through layers 0 ,1,and 2
    k0 = x
    k1 = nonlin(np.dot(k0, syn0))
    k2 = nonlin(np.dot(k1, syn1))
    
    #how much did we miss the target value?
    
    k2_error = y - k2
    
    if(j% 10000) ==0:
        print ("Error:" +str(np.mean(np.abs(k2_error))))
    
    #in what direction is the target value?
    k2_delta = k2_error*nonlin(k2, deriv=True)
    
    # how much did each 11 vale contribute to 12 error
    k1_error = k2_delta.dot(syn1.T)
    
    k1_delta =k1_error * nonlin(k1,deriv= True)
    
    syn1 += k1.T.dot(k2_delta)
    syn0 += k0.T.dot(k1_delta)
    
    

Error:0.501096575888
Error:0.00867680748564
Error:0.00584719148289
Error:0.00467599423846
Error:0.00399963912987
Error:0.00354703984153
